export interface Project {
  id: string;
  name: string;
  description: string;
  tags: string[];
  stars: string;
  language: string;
  github: string;
  author: string;
  trending: boolean;
  featured: boolean;
  review: string;
  emoji: string;
}

export const projects: Project[] = [
  {
    id: "1",
    name: "awesome-openclaw-skills-CN",
    description: "🇨🇳 中文开发者友好的 OpenClaw Skills 精选 | 含国产模型接入指南（DeepSeek/Qwen/GLM/Moonshot）| 2868+ Skills 分类整理",
    tags: ["Skills", "中文", "Agent"],
    stars: "111",
    language: "Markdown",
    github: "https://github.com/AIPMAndy/awesome-openclaw-skills-CN",
    author: "AI 酋长Andy",
    trending: true,
    featured: true,
    review: "2868+ Skills 分类整理，中文开发者入门 OpenClaw 的最佳资源。",
    emoji: "🇨🇳",
  },
  {
    id: "2",
    name: "LivePPT",
    description: "🎬 把 PPT 变成电影级网页演示 | Transform slides into cinematic web showcases",
    tags: ["Python", "PPT", "前端"],
    stars: "76",
    language: "Python",
    github: "https://github.com/AIPMAndy/LivePPT",
    author: "AI 酋长Andy",
    trending: true,
    featured: true,
    review: "PPT 转网页演示的黑科技，让静态幻灯片变成交互式网页。",
    emoji: "🎬",
  },
  {
    id: "3",
    name: "dna-memory",
    description: "🧬 让 AI Agent 像人脑一样学习成长 | Memory that learns, forgets, and evolves",
    tags: ["Python", "Agent", "Memory"],
    stars: "71",
    language: "Python",
    github: "https://github.com/AIPMAndy/dna-memory",
    author: "AI 酋长Andy",
    trending: true,
    featured: true,
    review: "AI 记忆系统的突破，三层记忆架构+主动遗忘机制。",
    emoji: "🧬",
  },
  {
    id: "4",
    name: "goskill",
    description: "🎯 Goal-driven execution helper for long-running tasks and explicit success criteria",
    tags: ["Python", "Agent", "Skills"],
    stars: "59",
    language: "Python",
    github: "https://github.com/AIPMAndy/goskill",
    author: "AI 酋长Andy",
    trending: true,
    featured: false,
    review: "目标驱动的任务执行框架，让 AI Agent 持续工作直到完成。",
    emoji: "🎯",
  },
  {
    id: "5",
    name: "PageSkill",
    description: "文章排版神器 - 一键生成精美排版",
    tags: ["TypeScript", "排版", "工具"],
    stars: "42",
    language: "TypeScript",
    github: "https://github.com/AIPMAndy/PageSkill",
    author: "AI 酋长Andy",
    trending: false,
    featured: true,
    review: "一键生成精美文章排版，支持多种模板和自定义样式。",
    emoji: "📐",
  },
  {
    id: "6",
    name: "ai-invest-agent",
    description: "🔥 AI 投资复盘系统 | 温度计量化估值 | A股/港股/美股 | 从拍脑袋到有体系",
    tags: ["Python", "投资", "AI"],
    stars: "40",
    language: "Python",
    github: "https://github.com/AIPMAndy/ai-invest-agent",
    author: "AI 酋长Andy",
    trending: true,
    featured: true,
    review: "AI 驱动的投资复盘系统，温度计量化估值模型。",
    emoji: "🔥",
  },
  {
    id: "7",
    name: "KnowMe",
    description: "🧬 Know yourself through AI conversations — Analyze MBTI personality from ChatGPT/Claude/DeepSeek chat history",
    tags: ["Python", "MBTI", "AI"],
    stars: "12",
    language: "Python",
    github: "https://github.com/AIPMAndy/KnowMe",
    author: "AI 酋长Andy",
    trending: false,
    featured: true,
    review: "通过 AI 对话分析 MBTI 性格，100% 本地私密。",
    emoji: "🧬",
  },
  {
    id: "8",
    name: "PPTskill",
    description: "🎨 AI 生成原生可编辑 PPTX — 无需设计技能 | AI-powered native editable PowerPoint generation",
    tags: ["Python", "PPT", "AI"],
    stars: "9",
    language: "Python",
    github: "https://github.com/AIPMAndy/PPTskill",
    author: "AI 酋长Andy",
    trending: false,
    featured: true,
    review: "AI 生成可编辑 PPT，直接输出 .pptx 文件。",
    emoji: "🎨",
  },
  {
    id: "9",
    name: "safeskill",
    description: "🔒 Security scanner for AI Skills | Detect dangerous commands, prompt injection, secrets, and suspicious patterns before install",
    tags: ["Python", "安全", "Skills"],
    stars: "8",
    language: "Python",
    github: "https://github.com/AIPMAndy/safeskill",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "AI Skills 安全扫描器，检测危险命令和注入攻击。",
    emoji: "🔒",
  },
  {
    id: "10",
    name: "CEOskill",
    description: "CEO decision-support skill for AI agents: strategy, trade-offs, debiasing, stakeholder mapping, and war gaming",
    tags: ["Python", "决策", "Skills"],
    stars: "5",
    language: "Python",
    github: "https://github.com/AIPMAndy/CEOskill",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "CEO 决策支持技能，战略分析、去偏差、利益相关者映射。",
    emoji: "👔",
  },
  {
    id: "11",
    name: "soskill",
    description: "🔍 SoSkill - 开源 Skill 搜索与聚合 | Open-source Skill Search & Aggregation",
    tags: ["Python", "Skills", "搜索"],
    stars: "4",
    language: "Python",
    github: "https://github.com/AIPMAndy/soskill",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "开源 Skill 搜索聚合工具，2700+ Skills 一键搜索。",
    emoji: "🔍",
  },
  {
    id: "12",
    name: "FreeToken",
    description: "🎁 收集各种免费 API Token 的获取方法和使用指南",
    tags: ["资源", "API", "免费"],
    stars: "3",
    language: "Markdown",
    github: "https://github.com/AIPMAndy/FreeToken",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "免费 AI API Token 大全，省钱必备。",
    emoji: "🎁",
  },
  {
    id: "13",
    name: "awesome-openclaw-use-cases-cn",
    description: "Chinese OpenClaw use cases: real-world workflows, prompts, configs, automation examples",
    tags: ["Shell", "Skills", "中文"],
    stars: "17",
    language: "Shell",
    github: "https://github.com/AIPMAndy/awesome-openclaw-use-cases-cn",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "中文 OpenClaw 实战案例集，真实工作流和自动化示例。",
    emoji: "📚",
  },
  {
    id: "14",
    name: "openclaw-install-guide",
    description: "🚀 OpenClaw installation guide with PipeLLMsetup (Claude/GPT/Gemini) for macOS/Linux/Windows",
    tags: ["Shell", "教程", "安装"],
    stars: "2",
    language: "Shell",
    github: "https://github.com/AIPMAndy/openclaw-install-guide",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "OpenClaw 安装指南，支持 macOS/Linux/Windows。",
    emoji: "🚀",
  },
  {
    id: "15",
    name: "BPClaw",
    description: "🎯 融资BP文档Agent体系 — 深度调研驱动、结构化评分、多格式产出",
    tags: ["Python", "BP", "融资"],
    stars: "2",
    language: "Python",
    github: "https://github.com/AIPMAndy/BPClaw",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "融资 BP 自动生成工具，深度调研+结构化评分。",
    emoji: "🎯",
  },
  {
    id: "16",
    name: "GoodPaper",
    description: "Open-source paper formatting helper for .docx/.docm manuscripts",
    tags: ["Python", "论文", "排版"],
    stars: "2",
    language: "Python",
    github: "https://github.com/AIPMAndy/GoodPaper",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "论文排版助手，自动检查和格式化 .docx 论文。",
    emoji: "📝",
  },
  {
    id: "17",
    name: "IPClawForHealth",
    description: "大健康行业创始人 IP 打造工具 - 用 AI 帮助健康行业创始人口播视频创作",
    tags: ["HTML", "IP", "健康"],
    stars: "2",
    language: "HTML",
    github: "https://github.com/AIPMAndy/IPClawForHealth",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "大健康行业 IP 打造工具，AI 辅助口播视频创作。",
    emoji: "🏥",
  },
  {
    id: "18",
    name: "teach-rd-product-handbook",
    description: "让研发具备产品意识的开源训练体系",
    tags: ["教程", "产品", "研发"],
    stars: "1",
    language: "Markdown",
    github: "https://github.com/AIPMAndy/teach-rd-product-handbook",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "研发转产品训练手册，培养产品思维。",
    emoji: "🧠",
  },
  {
    id: "19",
    name: "openclaw-doctor",
    description: "🔧 OpenClaw Gateway 诊断和修复工具 | Diagnostic and repair tool for OpenClaw Gateway",
    tags: ["Shell", "工具", "诊断"],
    stars: "1",
    language: "Shell",
    github: "https://github.com/AIPMAndy/openclaw-doctor",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "OpenClaw 诊断修复工具，一键排查问题。",
    emoji: "🔧",
  },
  {
    id: "20",
    name: "harness-engineering-bible",
    description: "The Definitive Guide to Harness Engineering: Browser Control, Multi-Agent Orchestration, and Information Retrieval",
    tags: ["TypeScript", "教程", "Agent"],
    stars: "1",
    language: "TypeScript",
    github: "https://github.com/AIPMAndy/harness-engineering-bible",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "Harness 工程权威指南，浏览器控制+多Agent编排。",
    emoji: "📖",
  },
  {
    id: "21",
    name: "shutupskill",
    description: "让 AI 不废话：GPT-5.4/Kimi 达到 Claude Opus 4.6 标准",
    tags: ["JavaScript", "Skills", "优化"],
    stars: "1",
    language: "JavaScript",
    github: "https://github.com/AIPMAndy/shutupskill",
    author: "AI 酋长Andy",
    trending: false,
    featured: false,
    review: "让 AI 精简回答，提升输出质量。",
    emoji: "🤐",
  },
];

export function getProjectById(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}

export function searchProjects(query: string): Project[] {
  const q = query.toLowerCase();
  return projects.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q))
  );
}

export function filterProjectsByTag(tag: string): Project[] {
  if (tag === "全部") return projects;
  return projects.filter((p) => p.tags.includes(tag));
}

export function getAllTags(): string[] {
  const tags = new Set<string>();
  projects.forEach((p) => p.tags.forEach((t) => tags.add(t)));
  return ["全部", ...Array.from(tags)];
}
